### ISSUE TITLE
Double free on transfer cancel

### ISSUE THREAD

**Issue by mgrabovsky** [dagargo/elektroid#105]
When I clicked the cancel button to interrupt a running download from Digitakt to my computer, the GUI application crashed. See output below for a backtrace from gdb.

Version: Elektroid 2.5.2 on Fedora 37

```
[... output abridged ...]
Core was generated by `elektroid'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kil
l.c:44
Downloading source file /usr/src/debug/glibc-2.36-9.fc37.x86_64/nptl/pthread_kill.c...
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
[Current thread is 1 (Thread 0x7f1bd23ff6c0 (LWP 47638))]
Missing separate debuginfos, use: dnf debuginfo-install libgcc-12.3.1-1.fc37.x86_64
(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kil
l.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {
          __val = {139757497629958}
        }
        ret = <optimized out>
#1  0x00007f1bf3dadec3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f1bf3d5da76 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f1bf3d477fc in __GI_abort () at abort.c:79
        save_stage = 1
        act = {
          __sigaction_handler = {
            sa_handler = 0x20,
            sa_sigaction = 0x20
          },
          sa_mask = {
            __val = {139758032109037, 166, 120, 32768, 5095747444345564416, 32768, 139757468248544, 139758037124531, 13
9758037090494, 12490, 1, 139758037124514, 139758037080381, 2, 13010195443300, 0}
          },
          sa_flags = -198962987,
          sa_restorer = 0x5618f319c4a0 <backend.lto_priv>
        }
#4  0x00007f1bf3da208e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f1bf3ebb465 "%s\n") at ../sysd
eps/posix/libc_fatal.c:155
        ap = {{
            gp_offset = 24,
            fp_offset = 22040,
            overflow_arg_area = 0x7f1bd23feac0,
            reg_save_area = 0x7f1bd23fea50
          }}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#5  0x00007f1bf3db7b9c in malloc_printerr (str=str@entry=0x7f1bf3ebdfe8 "free(): double free detected in tcache 2") at
malloc.c:5660
#6  0x00007f1bf3db9ee6 in _int_free (av=0x7f1bd4000030, p=0x7f1bd4011010, have_lock=0) at malloc.c:4469
        tmp = <optimized out>
        cnt = <optimized out>
        e = 0x7f1bd4011020
        tc_idx = 3
        size = 80
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
#7  0x00007f1bf3dbc363 in __GI___libc_free (mem=mem@entry=0x7f1bd4011020) at malloc.c:3385
        ar_ptr = <optimized out>
        p = 0x7f1bd4011010
        err = 2
#8  0x00007f1bf422688d in g_free (mem=0x7f1bd4011020) at ../glib/gmem.c:229
#9  0x00005618f31887fe in elektroid_download_task_runner (userdata=<optimized out>) at /usr/src/debug/elektroid-2.5.2-1
.fc37.x86_64/src/elektroid.c:2524
        res = <optimized out>
        array = 0x5618f41f02c0
        dst_path = 0x7f1bd4002d40 "/home/mgrabovsky/PIANO 01.wav"
        __FUNCTION__ = "elektroid_download_task_runner"
#10 0x00007f1bf424b982 in g_thread_proxy (data=0x5618f429e5e0) at ../glib/gthread.c:831
        thread = 0x5618f429e5e0
        __func__ = "g_thread_proxy"
#11 0x00007f1bf3dac12d in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {
          cancel_jmp_buf = {{
              jmp_buf = {139757468251840, -5693912998756008132, -136, 0, 140722418486544, 139757459861504, 567806738626
2699836, 5678141923951460156},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x0, 0x0},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = 0
            }
          }
        }
        not_first_call = <optimized out>
#12 0x00007f1bf3e2dbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb)
```

**Comment by dagargo** [comment]
Fixed in 21a5820bc6d3f20f20425d1372d51dae122c46a6.

Let me know if this works for you.
